### ISSUE TITLE
System.FormatException String '2020-06-16 15:30' was not recogonized as a valid DateTime

### ISSUE THREAD

**Issue by minahenin** [KevWK314/ThreeFourteen.AlphaVantage#10]
Replication Steps

var technicalData = await alphaVantage.Technicals.SimpleMovingAverage("SPY")
                .SetInterval(Interval.SixtyMinutes)
                .SetTimePeriod(13)
                .SetSeriesType(SeriesType.Close)
                .GetAsync();
![DateFromatError](https://user-images.githubusercontent.com/23611559/84868770-0cee0400-b032-11ea-81b2-69c1b82e36ce.png)

**Comment by minahenin** [comment]
at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String[] formats, IFormatProvider provider, DateTimeStyles style)
   at ThreeFourteen.AlphaVantage.Formats.ParseDateTime(String date)
   at ThreeFourteen.AlphaVantage.Response.JsonExtensions.ToTechnical(JProperty token, String valueKey)
   at ThreeFourteen.AlphaVantage.Builders.Technicals.BasicTechnicalBuilder.<Parse>b__9_0(JToken x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ThreeFourteen.AlphaVantage.Builders.Technicals.BasicTechnicalBuilder.Parse(JToken token)
   at ThreeFourteen.AlphaVantage.Builders.BuilderBase.<GetSeriesDataAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlphaVantageNugets.Program.<Main>d__0.MoveNext() in C:\Users\minahenin\source\repos\AlphaVantageNugets\Program.cs:line 14

**Comment by minahenin** [comment]
Found the Fix, looks like you need to add 
public const string DateTimeNoSecondsFormat = "yyyy-MM-dd HH:mm";//2020-06-16 15:30
in Formats.cs
